#33 ヘッダー修正
quest-academia/qa-rails-ec-training-apricot pull request #87
Opened 2023-06-03 10:06 UTC by tatata05

## このプルリクエストで何をしたのか
#33 

## 対象issue
- 作業したissueのURLをここに貼ること
#33 

## 重点的に見てほしいところ(不安なところ)

## 実装できなくて後回しにしたところ

rubocopの指摘に
```
app/helpers/sessions_helper.rb:18:5: W: Lint/UselessAssignment: Useless assignment to variable - current_user.
    current_user = nil
```
というものがありました。
ここで、binding.pryをしてみると、元々current_userはnilだったのですが、このコードは何を行なっているところなのでしょうか？

## チェックリスト
- [x] 動作確認は実行した?
- [x] rubocopは実行した？

## その他参考情報
- 実装する上で参考にしたサイトなどがあればリンクをここに貼ること

![スクリーンショット 2023-06-03 19 07 26](https://github.com/quest-academia/qa-rails-ec-training-apricot/assets/123435331/b91757d9-0617-4cf5-86d5-11763920028b)
![スクリーンショット 2023-06-03 19 07 14](https://github.com/quest-academia/qa-rails-ec-training-apricot/assets/123435331/99570f90-b172-43ef-a903-6509c01a979b)

2023-06-05 08:28 UTC, yuki-tachi0219 commented
>このlogoutを行うことと、リダイレクトを行う時の間に、今後何かコードを書いた時のためのリスクヘッジのようなものなのでしょうか？

はい。リスクヘッジですね。今後どんなコードが書かれるかわからないので。

2023-06-05 08:29 UTC, yuki-tachi0219 commented
rubocopのRails/I18nLocaleTexts についてはご認識の通りで、conrig/localesのymlファイルで日本語を定義して、そこから呼び出すようにしたいです

2023-06-05 11:25 UTC, tatata05 commented
https://github.com/quest-academia/qa-rails-ec-training-apricot/pull/87/commits/dc1c64c29d38f686d68fa9e6c9a5d8e2b3fad5bf
日本語化を行いました！

2023-06-05 11:36 UTC, tatata05 commented
https://github.com/quest-academia/qa-rails-ec-training-apricot/pull/87/commits/233aa53f2d9148930e2a5a148341aa404d111be9
コンフリクトを解消するためにpullを行ったところ、追加でrubocop指摘がありましたので、それも対応しました。

2023-06-08 07:10 UTC, tatata05 commented
https://github.com/quest-academia/qa-rails-ec-training-apricot/pull/87/commits/5c2cf56c8d52b499398fb18f41cf80e61b681c86
一部、ルーティングエラーがありましたので修正しました。

2023-06-08 07:58 UTC, yuki-tachi0219 requested changes
細かい指摘で恐縮ですが、
can'tと書けないならcannotにしたほうがいいです。
cantは不自然に見えます。

2023-06-08 07:58 UTC, yuki-tachi0219 commented on config/locales/flash_ja.yml
> +    cant_access: "他人の情報にアクセスすることはできません"
```suggestion
    cannot_access: "他人の情報にアクセスすることはできません"
```

2023-06-08 07:58 UTC, yuki-tachi0219 commented on app/controllers/users_controller.rb
> +        flash[:danger] = t("notice.cant_access")
```suggestion
        flash[:danger] = t("notice.cannot_access")
```

2023-06-08 09:50 UTC, yuki-tachi0219 approved these changes
LGTM!

2023-06-09 15:55 UTC, merged